root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  core-concepts/: README.md
  development-guide/: development/setup.md
  package-development/: development/data/README.md
  how-to/: guides/server-management.md
  reference/: reference/api.md
  contributing/: contributing/contributing.md