root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  development/: development/code-standards.md
  components/: components/data-pipeline.md
  deployment/: deployment/deployment-guide.md
  contributing/: contributing.md