version: "3"

vars:
  STACK: '{{default "stack-local" .STACK}}'

tasks:
  debug:
    dir: ./src/orchestration/dev/pipelines
    cmds:
      - echo "test is working ok"
      - ls

  etl_from_hf_to_lakefs:
    desc: "Task to etl from hf to lakefs"
    dir: "src/orchestration/dev/pipelines"
    cmds:
      - uv run ./data_etl.py 
  
  unsloth_finetuning_slm_pipeline:
    desc: "Task to finetune slm with unsloth"
    dir: "src/orchestration/dev/pipelines/ml"
    cmds:
      - uv sync --group ml-package
      - uv run task zenml:setup:all-integrations
      - uv run ./unsloth_finetune_slm.py 
