version: "3"
includes:
  integrations: integrations/Taskfile.yml
  secrets: secrets/Taskfile.yml
  setup: setup/Taskfile.yml
  test: test/Taskfile.yml
  utils: utils/Taskfile.yml
  pipelines: pipelines/Taskfile.yml

vars:
  ZENML_HOST: '{{default .ZENML_HOST "https://zenml.lmorbits.com"}}'

tasks:
  zenml-init:
    silent: false
    cmds:
      - |
        unset ZENML_STORE_URL
        unset ZENML_STORE_API_KEY
        unset ZENML_STORE_USERNAME
        unset ZENML_STORE_PASSWORD
        uv run zenml downgrade
        uv run zenml login {{.ZENML_HOST}} --refresh
      - uv run zenml init

  delete-test-pipelines:
    cmds:
      - uv run scripts/delete_pipelines.py -y --pipeline_name test_
      - uv run zenml artifact prune

  delete-dev-pipelines:
    cmds:
      - uv run scripts/delete_pipelines.py -y --pipeline_name dev_
      - uv run zenml artifact prune
