version: '3'
includes:
  integrations: integrations/Taskfile.yml

vars:
  ZENML_HOST: 
    sh: echo "${ZENML_HOST:-https://zenml.lmorbits.com}"

tasks:
  zenml-init:
    cmds:
      - uv run zenml init
      - uv run zenml login {{.ZENML_HOST}}