[project]
name = "serve"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "scikit-learn>=1.6.1",
  "litserve>=0.2.9",
  "sentence-transformers>=4.1.0",
  "fastembed>=0.6.1",
  "python-dotenv>=1.1.0",
  "go-task-bin>=3.43.3",
]
