version: '3'

includes:
  ml:
    taskfile: scripts/tasks/Taskfile.yml

tasks:
  gpu-instance-up:
    desc: "Launch the GPU instance "
    cmds:
      - uv sync --only-group dev 
      - uv run sky launch ./skypilot.yaml --name gpu-instance-ml
  gpu-instance-down:
    desc: "Shut down the GPU instance "
    cmds:
      - uv sync --only-group dev
      - uv run sky down --all -y
  ruff-format:
    desc: "Format the code using Ruff"
    cmds:
      - uvx ruff format
  
  init-git-ssh:
    desc: "Initialize Git SSH configuration for GitHub access"
    cmds:
      - cmd: test -f ~/.ssh/id_ed25519 || ssh-keygen -t ed25519 -C "parsa.miraghaie@gmail.com" -f ~/.ssh/id_ed25519 -N ""
        ignore_error: true
      - cmd: eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519
        ignore_error: true
      - git config --global user.email "parsa.miraghaie@gmail.com"
      - git config --global user.name "Parsa Miraghaie"
      - git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
      - cmd: cat ~/.ssh/id_ed25519.pub
        silent: true
      - echo "👆 Copy the above public key and add it to your GitHub account at https://github.com/settings/keys"
