version: "3"

tasks:
  create-secrets:
    desc: "Task to create all secrets"
    cmds:
      - task: create-data-secrets
      - task: create-ml-secrets

  create-data-secrets:
    desc: "Task to create data secrets"
    cmds:
      - uv run python src/orchestration/secrets/data_secrets.py --create

  delete-data-secrets:
    desc: "Task to delete data secrets"
    cmds:
      - uv run python src/orchestration/secrets/data_secrets.py --delete

  create-ml-secrets:
    desc: "Task to create ML secrets"
    cmds:
      - uv run python src/orchestration/secrets/ml_secrets.py
