[project]
name = "pyapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "parsa", email = "parsa.miraghaie@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pyapp"]

[dependency-groups]
chatbot = ["chatbot"] 

[tool.uv.workspace]
members = ["usecases/chatbot"]

[tool.uv.sources]
chatbot = { workspace = true }