steps:
  sky_finetuning_slm:
    enable_cache: false
    parameters:
      sky_config:
        resources:
          cloud: gcp 
          image_id: docker:nvcr.io/nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04
          accelerators: L4:1

        workdir: .

        setup: |
          echo "Hello, SkyPilot!"
          apt install git -y
          pip install uv
          uv python install 3.11
          echo "Running setup commands..."
          conda deactivate
          sudo apt update && apt install -y g++ make build-essential 
          cd /lmorbits/packages/orchestration

        
        run: |
          echo "--- Executing main task..."
          conda deactivate
          cd /lmorbits
          uv sync --group default
          uv run task ml:llama-cpp:llama-cpp-build
          cd /lmorbits/packages/orchestration
          uv run zenml init
          uv run task zenml:setup:stack-local STACK=stack-local-gpu
          uv run zenml stack list
          uv run task zenml:pipelines:dev:unsloth_finetuning_slm_pipeline
              
          

