version: "3"

tasks:
  simple-integrations:
    cmds:
      - uv run zenml integration install --uv mlflow -y
      - uv run zenml integration install --uv gcp -y

  all-integrations:
    cmds:
      - uv run zenml integration install --uv kubernetes -y
      - uv run zenml integration install --uv gcp -y
      - uv run zenml integration install --uv mlflow -y
      - uv run zenml integration install --uv huggingface -y

  sky-instance-integrations:
    cmds:
      - uv run zenml integration install --uv gcp -y
      - uv run zenml integration install --uv mlflow -y
