[project]
name = "serve"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-storage>=3.0.0",
    "llama-cpp-python>=0.3.7",
    "mlflow>=2.20.1",
    "tqdm>=4.67.1",
]

[project.scripts]
serve = "serve:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
