[project]
name = "serve"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.3",
    "google-cloud-storage",
    "llama-cpp-python>=0.3.7",
    "loguru>=0.7.3",
    "mlflow>=2.20.1",
    "tqdm>=4.67.1",
]

[project.scripts]
serve = "serve.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
